FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
COPY . build
RUN cd build && cp bashrc /root/.bashrc && cp sources.list /etc/apt/sources.list && apt-get update && apt-get install -y python3-pip git libgl1
RUN pip install -r requirements.txt -i https://mirrors.nju.edu.cn/pypi/web/simple/

# it should be run: 
# docker build -t mm_hal:1.2 .