FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
COPY . build
RUN cd build && cp sources.list /etc/apt/sources.list && apt-get update && apt-get install -y python3-pip git
RUN pip install -r requirements.txt -i https://mirrors.nju.edu.cn/pypi/web/simple/

# it should be run: 
# docker build -t mm_hal:1.0 .
# docker run --gpus all -it -v .:/workspace/hal mm_hal:1.0 -v /data/cache/huggingface:/root/.cache/huggingface -v /data/cache/torch:/root/.cache/torch